name: app_bloc_note
description: TP Flutter ESGI 4AL.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  google_fonts: ^3.0.1
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  path: ^1.7.0
  path_provider: ^2.0.11
  provider: ^6.0.3
  sqflite: ^2.0.2+1
  url_launcher: ^6.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/

