name: flutterApk
on:
  push:
    paths: './app_bloc_note/**'
defaults:
  run:
    working-directory: ./app_bloc_note

jobs:
  building_apk:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build apk